# Navigation

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the first project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893).

### 1. Start the Environment

We begin by importing some necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
import numpy as np

from unityagents import UnityEnvironment
from dqn_brain_agent import BrainAgent, train_dqn
from training_analysis import plot_results

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Banana.app"`
- **Windows** (x86): `"path/to/Banana_Windows_x86/Banana.exe"`
- **Windows** (x86_64): `"path/to/Banana_Windows_x86_64/Banana.exe"`
- **Linux** (x86): `"path/to/Banana_Linux/Banana.x86"`
- **Linux** (x86_64): `"path/to/Banana_Linux/Banana.x86_64"`
- **Linux** (x86, headless): `"path/to/Banana_Linux_NoVis/Banana.x86"`
- **Linux** (x86_64, headless): `"path/to/Banana_Linux_NoVis/Banana.x86_64"`

For instance, if you are using a Mac, then you downloaded `Banana.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Banana.app")
```

In [2]:
env = UnityEnvironment(file_name="./Banana_Linux/Banana.x86_64")

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: BananaBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 37
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

### 2. Create Learning Agent and Examine Parameters

The simulation contains a single agent that navigates a large environment.  The agent is based on [ML-Agents's Brain class](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/brain.py) and deep neural network defined in [PyTorch](https://pytorch.org/). 

The agent is instantiated as

In [3]:
# create learning brain agent
brain_name = env.brain_names[0]
vanilla_agent = BrainAgent(brain_name, env.brains[brain_name])

At each time step, the agent has four actions at its disposal:
- `0` - walk forward 
- `1` - walk backward
- `2` - turn left
- `3` - turn right

The state space has `37` dimensions and contains the agent's velocity, along with ray-based perception of objects around agent's forward direction.  A reward of `+1` is provided for collecting a yellow banana, and a reward of `-1` is provided for collecting a blue banana. 

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=True)[vanilla_agent.name]

# number of agents in the environment
print('Number of agents:', len(env_info.agents))

# number of actions
print('Number of actions:', vanilla_agent.brain.vector_action_space_size)

# examine the state space 
print('States look like:', env_info.vector_observations[0])
print('States have length:', vanilla_agent.brain.vector_observation_space_size)

Number of agents: 1
Number of actions: 4
States look like: [1.         0.         0.         0.         0.84408134 0.
 0.         1.         0.         0.0748472  0.         1.
 0.         0.         0.25755    1.         0.         0.
 0.         0.74177343 0.         1.         0.         0.
 0.25854847 0.         0.         1.         0.         0.09355672
 0.         1.         0.         0.         0.31969345 0.
 0.        ]
States have length: 37


### 3. Train the Banana Navigation BrainAgent

The `dqn_brain_agent.py:train_dqn` trains a `BrainAgent` within a specified `env` using Deep Q-Learning.

In [ ]:
# train brain agent with 'vanilla' deep q-learning
vanilla_scores = train_dqn(env, vanilla_agent, prefix='vanilla')

In [5]:
# train brain agent with double deep q-learning
ddqn_agent = BrainAgent(brain_name, env.brains[brain_name], ddqn=True)
ddqn_scores = train_dqn(env, ddqn_agent, prefix='ddqn')

tensor([[ 0.0380,  0.1298, -0.0399,  0.0708],
        [ 0.0762,  0.1121,  0.0041, -0.0269],
        [ 0.0675,  0.1164,  0.0015, -0.0214],
        [ 0.0475,  0.1370, -0.0227,  0.0778],
        [ 0.0449,  0.1368, -0.0366,  0.0756],
        [ 0.0365,  0.1360, -0.0336,  0.0744],
        [ 0.0334,  0.1370, -0.0496,  0.0883],
        [ 0.0701,  0.1153, -0.0011, -0.0099],
        [ 0.0818,  0.1271,  0.0136,  0.0241],
        [ 0.0283,  0.1489, -0.0458,  0.0841],
        [ 0.0185,  0.1402, -0.0302,  0.0810],
        [ 0.0352,  0.1404, -0.0271,  0.0834],
        [ 0.0469,  0.1353, -0.0410,  0.1116],
        [ 0.0661,  0.1427, -0.0412,  0.0023],
        [ 0.0705,  0.1211, -0.0099,  0.0066],
        [ 0.0141,  0.1502, -0.0544,  0.0703],
        [ 0.0743,  0.1173,  0.0068,  0.0308],
        [ 0.0363,  0.1373, -0.0447,  0.0676],
        [ 0.0125,  0.1629, -0.0389,  0.0522],
        [ 0.0334,  0.1258, -0.0198,  0.0795],
        [ 0.0678,  0.1484, -0.0452, -0.0095],
        [ 0.0572,  0.1280, -0.0355

tensor([[ 0.0533,  0.0852,  0.0167,  0.0710],
        [ 0.0705,  0.0362,  0.0566,  0.0211],
        [ 0.0438,  0.0914,  0.0214,  0.0624],
        [ 0.0394,  0.0579,  0.0181,  0.0666],
        [ 0.0433,  0.0719,  0.0549,  0.0497],
        [ 0.0502,  0.0511,  0.0609,  0.0628],
        [ 0.0530,  0.0513,  0.0610,  0.0607],
        [ 0.0603,  0.0698,  0.0357,  0.0546],
        [ 0.0693,  0.0559,  0.0532,  0.0447],
        [ 0.0498,  0.0340,  0.0379,  0.0429],
        [ 0.0466,  0.0705,  0.0462,  0.0691],
        [ 0.0664,  0.0065,  0.0749,  0.0071],
        [ 0.0716,  0.0213,  0.0583,  0.0365],
        [ 0.0695, -0.0041,  0.0911, -0.0160],
        [ 0.0590,  0.0222,  0.0670,  0.0828],
        [ 0.0538,  0.0048,  0.0867,  0.0222],
        [ 0.0664,  0.0595,  0.0491,  0.0445],
        [ 0.0513,  0.0998,  0.0146,  0.0619],
        [ 0.0532,  0.0696,  0.0223,  0.0572],
        [ 0.0451,  0.0793,  0.0237,  0.0654],
        [ 0.0326,  0.0956,  0.0291,  0.0885],
        [ 0.0706,  0.0641,  0.0427

tensor(1.00000e-02 *
       [[ 3.4091,  4.9945,  5.2255,  6.5501],
        [ 4.1838,  8.2690,  4.0208,  7.7912],
        [ 3.7400,  6.5268,  5.5028,  5.2417],
        [ 3.6682,  6.0650,  5.3016,  4.5068],
        [ 4.2997,  3.7289,  2.3813,  5.0560],
        [ 5.3267,  5.1897,  3.0999,  5.3473],
        [ 3.8397,  3.1904,  8.3784,  4.7281],
        [ 3.3961,  2.9986,  7.4999,  5.1521],
        [ 3.5403,  4.5761,  7.9007,  5.7370],
        [ 4.1187,  6.3585,  6.0953,  6.7630],
        [ 4.4580,  2.8786,  2.6403,  4.3223],
        [ 4.5636,  0.5251,  4.5396,  1.4122],
        [ 4.6720,  1.3872,  9.1906,  4.5134],
        [ 4.7577,  6.1761,  2.7497,  6.0466],
        [ 3.3715,  8.6948,  3.6090,  7.7625],
        [ 5.6966,  4.7926,  4.6254,  4.7135],
        [ 4.1768,  5.4659,  4.2356,  5.8125],
        [ 4.9308, -0.3319,  5.4944,  0.1001],
        [ 5.6566,  1.4993,  4.4632,  4.1043],
        [ 4.4609,  6.9833,  3.3970,  5.8781],
        [ 6.2016,  5.3478,  4.2092,  5.8016],
        [ 3.8

tensor([ 2,  1,  1,  2,  2,  3,  3,  2,  2,  0,  2,  3,  0,  0,
         0,  3,  2,  1,  3,  0,  0,  1,  1,  0,  0,  0,  0,  1,
         2,  1,  0,  0,  2,  0,  2,  2,  0,  2,  3,  3,  1,  1,
         3,  0,  1,  2,  1,  2,  1,  3,  3,  2,  0,  2,  3,  0,
         0,  1,  2,  0,  1,  1,  3,  1])
tensor(1.00000e-02 *
       [[ 5.5001,  7.5734,  4.1505,  6.0506],
        [ 4.5312,  7.8887,  3.3971,  5.1668],
        [ 6.9270,  4.8305,  7.1601,  0.6365],
        [ 5.0951,  3.1589,  4.9075,  3.3738],
        [ 5.4119,  7.3069,  2.1856,  6.3241],
        [ 5.8676,  7.4525,  3.3090,  6.2256],
        [ 6.5441,  5.3394,  6.3832,  5.1362],
        [ 4.5455,  5.7955,  3.3978,  7.6333],
        [ 4.0247,  7.6489,  0.3140,  8.6737],
        [ 6.2625,  5.6895,  2.7842,  6.3111],
        [ 4.9440,  5.1374,  2.5891,  6.0314],
        [ 6.3085,  6.4709,  4.9862,  5.1699],
        [ 5.7953,  6.1249,  3.3996,  6.0121],
        [ 5.6716,  3.4659,  5.8145,  5.1190],
        [ 6.4150,  5.0655,  3.7446,  7

tensor(1.00000e-02 *
       [[ 3.5289,  4.3194,  5.7655,  1.6721],
        [ 4.2034,  6.0453,  4.5229,  4.2150],
        [ 4.4597,  6.5850,  4.0487,  5.2342],
        [ 4.8354,  4.8353,  6.4532,  5.1936],
        [ 5.1272,  5.3206,  4.6643,  5.5241],
        [ 5.3384,  4.1817,  6.2688,  3.3924],
        [ 4.8533,  4.9530,  5.4083,  4.2273],
        [ 4.3885,  5.1087,  2.7516,  3.7071],
        [ 4.6760,  5.4324,  3.7721,  5.5854],
        [ 4.7182,  5.1531,  6.0093,  3.6356],
        [ 5.1810,  4.6760,  4.9181,  5.2613],
        [ 4.0734,  6.5575,  4.3278,  6.3109],
        [ 4.0869,  5.7430,  4.2347,  4.9899],
        [ 5.5642,  4.2907,  5.6871,  4.8703],
        [ 5.1997,  4.0729,  5.0597,  6.6035],
        [ 5.2941,  2.1125,  5.4586,  4.3628],
        [ 5.5371,  4.3102,  6.2251,  4.6527],
        [ 4.8473,  4.8562,  5.1915,  4.3758],
        [ 4.1650,  7.4763,  1.3658,  7.0321],
        [ 4.4712,  5.4717,  4.3391,  4.2092],
        [ 5.4885,  4.6365,  6.3606,  4.2768],
        [ 4.8

tensor(1.00000e-02 *
       [[ 6.9159,  3.7030,  5.5297,  4.3766],
        [ 4.6653,  4.4802,  5.0672,  4.5224],
        [ 4.9522,  3.6630,  5.7847,  4.0210],
        [ 4.1317,  3.9456,  4.7852,  4.7959],
        [ 4.2512,  3.7470,  5.0509,  4.6391],
        [ 5.5257,  4.2607,  5.3078,  4.5805],
        [ 6.4327,  4.8080,  4.9152,  4.2911],
        [ 4.4301,  6.0017,  4.0757,  5.5079],
        [ 4.4973,  5.6216,  4.5122,  4.6104],
        [ 4.9724,  7.2612,  4.2556,  5.0764],
        [ 4.3903,  4.9441,  4.6788,  4.7588],
        [ 3.3129,  5.2399,  4.2417,  4.0074],
        [ 3.8735,  5.0377,  5.0377,  4.3171],
        [ 5.7842,  5.5881,  4.1196,  4.0564],
        [ 4.0505,  5.9824,  4.1325,  4.2668],
        [ 5.8124,  4.2776,  6.5992,  3.9054],
        [ 5.1351,  3.7628,  6.7145,  2.0105],
        [ 4.8384,  7.0559,  2.1443,  5.9818],
        [ 4.2285,  3.9118,  5.3611,  4.4134],
        [ 2.6146,  5.8858,  2.7797,  4.8369],
        [ 6.2671,  4.6373,  4.6578,  3.5777],
        [ 3.3

tensor(1.00000e-02 *
       [[ 5.6468,  5.5532,  3.8868,  5.1999],
        [ 4.6739,  6.2460,  5.0008,  5.0354],
        [ 5.5272,  5.6018,  5.9778,  4.2831],
        [ 5.6189,  5.3113,  4.6753,  4.3735],
        [ 5.4651,  6.0349,  4.2612,  4.6576],
        [ 5.7717,  5.2453,  4.7565,  4.1947],
        [ 4.4736,  4.0538,  5.9339,  5.0591],
        [ 4.8146,  5.2433,  5.2189,  5.8965],
        [ 4.6335,  5.0937,  5.4606,  5.4754],
        [ 6.6897,  4.6686,  3.9749,  5.4903],
        [ 4.5215,  6.1095,  4.4049,  4.3126],
        [ 4.6184,  6.2307,  4.7181,  5.6946],
        [ 4.2301,  6.1830,  4.6378,  5.4679],
        [ 5.6356,  4.5116,  6.8978,  3.2286],
        [ 4.6330,  7.4354,  4.6577,  4.8668],
        [ 4.9382,  6.1189,  3.4863,  5.0821],
        [ 5.8318,  5.1449,  4.4755,  4.7748],
        [ 5.2403,  3.8713,  6.0678,  5.3137],
        [ 5.0318,  5.0251,  5.7494,  5.6378],
        [ 5.0264,  6.8817,  2.6356,  5.6263],
        [ 4.8027,  4.4709,  4.0154,  5.9381],
        [ 4.9

tensor(1.00000e-02 *
       [[ 5.3030,  4.5055,  5.8762,  5.0614],
        [ 5.2665,  5.1189,  5.8307,  5.3741],
        [ 6.7081,  4.4787,  4.6620,  7.3124],
        [ 5.0128,  3.7317,  6.4954,  5.2365],
        [ 4.8770,  7.4395,  4.8984,  5.0900],
        [ 5.1287,  5.6226,  4.3474,  5.6532],
        [ 4.7420,  6.4179,  4.4582,  4.6702],
        [ 4.8733,  5.1235,  5.6681,  6.4659],
        [ 4.3169,  4.6261,  6.2668,  4.8154],
        [ 5.5001,  4.7344,  5.7924,  5.8061],
        [ 5.1543,  5.1277,  5.9488,  5.1054],
        [ 5.0700,  5.3621,  4.5364,  4.9020],
        [ 3.8757,  5.4095,  5.6611,  4.0787],
        [ 6.0899,  8.4864,  3.2860,  5.7673],
        [ 4.5501,  5.7122,  4.8531,  5.4137],
        [ 5.0729,  3.9234,  6.3293,  4.7989],
        [ 4.3351,  4.9393,  5.9599,  4.9538],
        [ 4.4119,  4.3325,  6.1936,  4.6326],
        [ 4.0604,  6.0657,  5.0561,  4.4570],
        [ 4.7838,  6.0795,  4.0169,  4.3047],
        [ 4.8303,  4.8974,  5.3971,  5.6753],
        [ 5.3

tensor(1.00000e-02 *
       [[ 5.3193,  5.1293,  5.9502,  4.5716],
        [ 6.3863,  8.2335,  3.1388,  5.5930],
        [ 5.2213,  4.9103,  5.8247,  4.4661],
        [ 4.4231,  6.1129,  4.7028,  4.9475],
        [ 5.7117,  4.5523,  5.4130,  4.5388],
        [ 5.4898,  4.2883,  5.7733,  5.0455],
        [ 4.9588,  5.3463,  4.4709,  4.8540],
        [ 5.0042,  4.8631,  4.9719,  4.0635],
        [ 4.8019,  4.7557,  5.7671,  4.5299],
        [ 5.3593,  5.0097,  5.9691,  4.7312],
        [ 5.4395,  6.0095,  5.4000,  4.7530],
        [ 4.5030,  6.3675,  5.2310,  4.8198],
        [ 5.5997,  4.8632,  5.8975,  5.2704],
        [ 5.3470,  4.7387,  5.3676,  5.2115],
        [ 4.9464,  5.1631,  4.9867,  4.3993],
        [ 5.7389,  5.9093,  4.3238,  5.0427],
        [ 4.8414,  4.7895,  6.2549,  4.8529],
        [ 4.9235,  5.4257,  4.1408,  5.0398],
        [ 4.8454,  4.7650,  5.4632,  4.3733],
        [ 5.0410,  4.9172,  4.2348,  5.5063],
        [ 5.3525,  5.2344,  4.7001,  5.1421],
        [ 4.1

tensor(1.00000e-02 *
       [[ 4.9114,  4.8306,  4.1159,  5.3014],
        [ 5.7804,  6.1495,  3.4972,  4.5232],
        [ 3.9664,  4.9511,  6.2489,  4.8032],
        [ 3.4659,  5.9345,  3.1006,  5.5053],
        [ 4.5990,  5.1918,  4.2703,  5.4385],
        [ 4.9732,  4.5615,  4.9719,  5.4367],
        [ 5.1739,  4.2544,  5.9233,  5.2551],
        [ 5.1129,  4.2618,  5.6312,  4.6220],
        [ 5.0504,  5.0187,  4.6561,  6.4823],
        [ 5.1288,  4.0401,  5.4040,  4.6953],
        [ 5.2322,  4.6722,  4.4156,  5.1197],
        [ 4.9533,  4.7082,  4.9052,  5.2807],
        [ 5.7294,  3.6212,  2.9752,  4.3443],
        [ 4.4176,  4.1906,  5.3391,  4.6163],
        [ 4.9378,  4.4920,  5.3569,  4.9145],
        [ 4.0975,  5.0470,  4.8075,  4.1093],
        [ 4.6779,  5.7284,  4.6227,  5.2566],
        [ 4.8134,  5.0853,  3.9796,  5.1006],
        [ 4.6005,  4.1972,  5.4681,  4.6114],
        [ 4.8333,  5.1439,  4.7732,  5.4371],
        [ 5.5440,  5.4334,  5.2031,  5.0079],
        [ 5.1

tensor(1.00000e-02 *
       [[ 3.8165,  5.5080,  3.8205,  5.9626],
        [ 4.4439,  7.2983,  4.5311,  5.4726],
        [ 4.9894,  4.7124,  5.2453,  5.4300],
        [ 4.6193,  5.2933,  4.7129,  5.4687],
        [ 4.4550,  6.8687,  5.6361,  5.2213],
        [ 4.4556,  4.1065,  5.6785,  4.5875],
        [ 5.3434,  5.7159,  5.8370,  4.4448],
        [ 4.6185,  6.8779,  3.7067,  4.8994],
        [ 5.2778,  5.3665,  4.8164,  4.8832],
        [ 4.8485,  7.1617,  2.5404,  5.3024],
        [ 3.9583,  8.6588,  4.2377,  5.4331],
        [ 5.4282,  4.8629,  4.8848,  4.6217],
        [ 4.3435,  5.2030,  4.5715,  5.3371],
        [ 4.5548,  7.4717,  5.0395,  3.4924],
        [ 4.5178,  4.7134,  4.6186,  5.3275],
        [ 5.0413,  6.1412,  3.0054,  4.9794],
        [ 4.5925,  5.5087,  4.6182,  5.7547],
        [ 5.6104,  6.6187,  3.7073,  4.6942],
        [ 4.5655,  5.1254,  4.9812,  5.5448],
        [ 5.7535,  3.7648,  5.3374,  4.3932],
        [ 4.2006,  5.4923,  5.4185,  5.9435],
        [ 4.8

tensor([[ 0.0501,  0.0613,  0.0581,  0.0535],
        [ 0.0682,  0.0589,  0.0612,  0.0593],
        [ 0.0500,  0.0871,  0.0485,  0.0610],
        [ 0.0516,  0.0887,  0.0422,  0.0767],
        [ 0.0529,  0.0774,  0.0474,  0.0558],
        [ 0.0542,  0.0696,  0.0604,  0.0557],
        [ 0.0363,  0.0955,  0.0573,  0.0556],
        [ 0.0610,  0.0786,  0.0537,  0.0656],
        [ 0.0554,  0.0809,  0.0515,  0.0491],
        [ 0.0471,  0.0994,  0.0557,  0.0639],
        [ 0.0641,  0.0696,  0.0481,  0.0734],
        [ 0.0471,  0.0878,  0.0511,  0.0754],
        [ 0.0582,  0.0465,  0.0669,  0.0544],
        [ 0.0413,  0.0920,  0.0573,  0.0564],
        [ 0.0522,  0.0662,  0.0493,  0.0648],
        [ 0.0491,  0.0594,  0.0606,  0.0627],
        [ 0.0483,  0.0843,  0.0575,  0.0703],
        [ 0.0554,  0.0761,  0.0272,  0.0596],
        [ 0.0592,  0.0444,  0.0605,  0.0595],
        [ 0.0642,  0.0546,  0.0726,  0.0556],
        [ 0.0484,  0.0979,  0.0488,  0.0645],
        [ 0.0483,  0.0944,  0.0484

tensor([[ 0.0342,  0.1164,  0.0413,  0.0656],
        [ 0.0616,  0.0515,  0.0574,  0.0536],
        [ 0.0619,  0.0453,  0.0657,  0.0435],
        [ 0.0425,  0.1016,  0.0426,  0.0651],
        [ 0.0700,  0.0497,  0.0751,  0.0411],
        [ 0.0604,  0.0530,  0.0615,  0.0481],
        [ 0.0597,  0.1036,  0.0480,  0.0441],
        [ 0.0435,  0.1010,  0.0449,  0.0561],
        [ 0.0666,  0.0587,  0.0611,  0.0507],
        [ 0.0613,  0.0489,  0.0641,  0.0427],
        [ 0.0547,  0.0956,  0.0427,  0.0536],
        [ 0.0611,  0.0671,  0.0556,  0.0593],
        [ 0.0480,  0.1033,  0.0428,  0.0592],
        [ 0.0559,  0.0693,  0.0525,  0.0525],
        [ 0.0658,  0.0593,  0.0494,  0.0453],
        [ 0.0590,  0.0810,  0.0530,  0.0444],
        [ 0.0283,  0.1229,  0.0497,  0.0621],
        [ 0.0616,  0.0690,  0.0379,  0.0357],
        [ 0.0585,  0.0475,  0.0609,  0.0503],
        [ 0.0597,  0.0908,  0.0442,  0.0706],
        [ 0.0632,  0.0362,  0.0725,  0.0356],
        [ 0.0539,  0.0889,  0.0401

tensor([[ 0.0773,  0.0396,  0.0612,  0.0484],
        [ 0.0679,  0.0628,  0.0591,  0.0504],
        [ 0.0703,  0.0709,  0.0476,  0.0499],
        [ 0.0597,  0.0631,  0.0425,  0.0525],
        [ 0.0672,  0.0572,  0.0503,  0.0476],
        [ 0.0756,  0.0673,  0.0517,  0.0762],
        [ 0.0478,  0.0391,  0.0163,  0.0532],
        [ 0.0637,  0.0741,  0.0421,  0.0512],
        [ 0.0101,  0.1557,  0.0383,  0.0539],
        [ 0.0606,  0.1018,  0.0562,  0.0392],
        [ 0.0897,  0.0521,  0.0443,  0.0513],
        [ 0.0550,  0.0907,  0.0368,  0.0628],
        [ 0.0574,  0.0355,  0.0347,  0.0534],
        [ 0.0594,  0.0924,  0.0450,  0.0485],
        [ 0.0554,  0.0490,  0.0363,  0.0602],
        [ 0.0422,  0.0424,  0.0106,  0.0596],
        [ 0.0818,  0.0696,  0.0410,  0.0521],
        [ 0.0575,  0.0539,  0.0469,  0.0579],
        [ 0.0574,  0.0360,  0.0330,  0.0527],
        [ 0.0667,  0.0931,  0.0603,  0.0378],
        [ 0.0525,  0.0428,  0.0287,  0.0626],
        [ 0.0545,  0.0690,  0.0474

tensor(1.00000e-02 *
       [[ 4.5833,  5.7733,  4.1588,  5.0815],
        [ 3.9975,  4.5396,  2.5973,  5.1356],
        [ 3.0135,  5.5964,  1.0020,  5.4223],
        [ 6.1477,  6.8420,  5.7357,  5.1288],
        [ 7.1819,  4.5737,  5.9473,  4.8614],
        [ 8.1938,  4.4262,  4.9086,  4.5072],
        [ 6.8826,  3.7001,  5.4438,  4.0750],
        [ 2.8130,  6.6644,  2.9518,  5.1242],
        [ 3.8289,  5.6585,  1.9863,  4.6847],
        [ 6.2270,  4.3183,  5.4048,  4.0497],
        [ 6.6272,  6.5338,  5.2093,  6.2933],
        [ 9.6631,  3.2410,  7.3864,  4.9139],
        [ 6.0015,  7.2837,  5.1814,  5.3658],
        [ 2.8231,  6.3988,  2.4522,  5.7573],
        [ 7.4672,  5.7498,  7.3740,  5.4872],
        [ 7.0070,  6.3360,  6.1247,  4.9180],
        [ 5.3130,  6.4388,  3.1896,  4.4633],
        [ 6.2490,  5.5441,  6.4729,  4.2369],
        [ 4.4506,  5.5576,  3.8119,  4.8215],
        [ 6.9078,  4.5566,  5.0558,  4.3155],
        [ 3.4468,  6.8936,  3.0030,  5.2651],
        [ 6.1

tensor([[ 0.0319,  0.1024,  0.0083,  0.0443],
        [ 0.0257,  0.1158, -0.0073,  0.0419],
        [ 0.0407,  0.0836,  0.0275,  0.0440],
        [ 0.0396,  0.0711,  0.0360,  0.0473],
        [ 0.0372,  0.0793,  0.0165,  0.0473],
        [ 0.0390,  0.0739,  0.0297,  0.0373],
        [ 0.0364,  0.0631,  0.0393,  0.0359],
        [ 0.0600,  0.0592,  0.0431,  0.0579],
        [ 0.0432,  0.0758,  0.0392,  0.0466],
        [ 0.0412,  0.0775,  0.0475,  0.0608],
        [ 0.0390,  0.0964,  0.0107,  0.0466],
        [ 0.0443,  0.0755,  0.0481,  0.0464],
        [ 0.0494,  0.0624,  0.0434,  0.0455],
        [ 0.0483,  0.0762,  0.0442,  0.0519],
        [ 0.0545,  0.0689,  0.0474,  0.0448],
        [ 0.0421,  0.0886,  0.0490,  0.0501],
        [ 0.0477,  0.0780,  0.0491,  0.0537],
        [ 0.0438,  0.0503,  0.0436,  0.0406],
        [ 0.0731,  0.0510,  0.0588,  0.0492],
        [ 0.0366,  0.0835,  0.0103,  0.0505],
        [ 0.0427,  0.0767,  0.0446,  0.0502],
        [ 0.0432,  0.0640,  0.0363

tensor(1.00000e-02 *
       [[ 6.8327,  4.5350,  4.1778,  5.7616],
        [ 6.1913,  3.9678,  3.1874,  5.1182],
        [ 5.5051,  4.6195,  4.7108,  4.6532],
        [ 6.2179,  5.9820,  5.0554,  6.4212],
        [ 5.8873,  2.6214,  4.3092,  4.8978],
        [ 5.9840,  7.4356,  0.9753,  5.8783],
        [ 6.1101,  7.1956,  4.3498,  6.1705],
        [ 6.0377,  7.0494,  4.4630,  4.3974],
        [ 6.4568,  5.1138,  5.4011,  5.9751],
        [ 6.3212,  4.8734,  5.5347,  5.2235],
        [ 6.2353,  5.4524,  4.3339,  6.0435],
        [ 4.8332,  4.5029,  5.4252,  4.3376],
        [ 6.9042,  4.6328,  4.9052,  5.1384],
        [ 6.2262,  3.8081,  4.4038,  5.6926],
        [ 5.4919,  3.5016,  5.0757,  4.8869],
        [ 6.1664,  4.4860,  4.4063,  5.1941],
        [ 5.5008,  7.3407,  3.4589,  5.3068],
        [ 6.4961,  5.6398,  5.1552,  5.5856],
        [ 7.3701,  3.0470,  3.4429,  3.7067],
        [ 6.1825,  5.7698,  3.2702,  5.3858],
        [ 7.1683,  4.4668,  3.2999,  5.6282],
        [ 6.9

tensor([[ 0.0559,  0.0512,  0.0591,  0.0613],
        [ 0.0654,  0.0527,  0.0524,  0.0579],
        [ 0.0433,  0.0759, -0.0245,  0.0630],
        [ 0.0314,  0.0563,  0.0627,  0.0590],
        [ 0.0499,  0.0845, -0.0182,  0.0609],
        [ 0.0409,  0.0492,  0.0494,  0.0566],
        [ 0.0300,  0.0837,  0.0530,  0.0685],
        [ 0.0579,  0.0585, -0.0087,  0.0520],
        [ 0.0460,  0.0449,  0.0438,  0.0558],
        [ 0.0457,  0.0704,  0.0322,  0.0637],
        [ 0.0299,  0.0764,  0.0529,  0.0486],
        [ 0.0625,  0.0699, -0.0283,  0.0563],
        [ 0.0610,  0.0508,  0.0201,  0.0627],
        [ 0.0512,  0.0672,  0.0261,  0.0597],
        [ 0.0564,  0.0528,  0.0480,  0.0525],
        [ 0.0603,  0.0622,  0.0619,  0.0809],
        [ 0.0545,  0.0658,  0.0442,  0.0597],
        [ 0.0517,  0.0539,  0.0466,  0.0603],
        [ 0.0253,  0.0689,  0.0485,  0.0548],
        [ 0.0638,  0.0532,  0.0459,  0.0605],
        [ 0.0182,  0.1019,  0.0538,  0.0626],
        [ 0.0516,  0.0547,  0.0300

tensor([[ 0.0502,  0.0418,  0.0414,  0.0510],
        [ 0.0544,  0.0653,  0.0480,  0.0516],
        [ 0.0500,  0.0621,  0.0571,  0.0543],
        [ 0.0439,  0.0646,  0.0443,  0.0554],
        [ 0.0586,  0.0402,  0.0595,  0.0406],
        [ 0.0511,  0.0763, -0.0306,  0.0416],
        [ 0.0586,  0.0521,  0.0592,  0.0557],
        [ 0.0467,  0.0550,  0.0373,  0.0456],
        [ 0.0674,  0.0470,  0.0587,  0.0550],
        [ 0.0447,  0.0801,  0.0607,  0.0531],
        [ 0.0365,  0.0964, -0.0599,  0.0473],
        [ 0.0698,  0.0555,  0.0575,  0.0683],
        [ 0.0621,  0.0424,  0.0272,  0.0526],
        [ 0.0609,  0.0614,  0.0414,  0.0572],
        [ 0.0605,  0.0498,  0.0531,  0.0444],
        [ 0.0396,  0.1024,  0.0538,  0.0485],
        [ 0.0394,  0.1152,  0.0612,  0.0648],
        [ 0.0564,  0.0488,  0.0162,  0.0523],
        [ 0.0464,  0.0616, -0.0275,  0.0404],
        [ 0.0540,  0.0581, -0.0145,  0.0440],
        [ 0.0563,  0.0496,  0.0566,  0.0501],
        [ 0.0552,  0.0500, -0.0033

tensor([[ 0.0576,  0.0370,  0.0582,  0.0497],
        [ 0.0845,  0.0345,  0.0492,  0.0537],
        [ 0.0555,  0.0402,  0.0629,  0.0494],
        [ 0.0560,  0.0518,  0.0038,  0.0501],
        [ 0.0605,  0.0529,  0.0495,  0.0609],
        [ 0.0578,  0.0572, -0.0047,  0.0521],
        [ 0.0474,  0.0313,  0.0456,  0.0486],
        [ 0.0737,  0.0575,  0.0540,  0.0472],
        [ 0.0970,  0.0047,  0.0575,  0.0505],
        [ 0.0550,  0.0611,  0.0565,  0.0482],
        [ 0.0877,  0.0257,  0.0589,  0.0589],
        [ 0.0524,  0.0414,  0.0447,  0.0519],
        [ 0.0580,  0.0437,  0.0524,  0.0462],
        [ 0.0569,  0.0431,  0.0372,  0.0505],
        [ 0.0825,  0.0401,  0.0446,  0.0697],
        [ 0.0512,  0.0556,  0.0461,  0.0412],
        [ 0.0847,  0.0246,  0.0574,  0.0589],
        [ 0.0529,  0.0435,  0.0485,  0.0490],
        [ 0.0501,  0.0551,  0.0560,  0.0495],
        [ 0.0561,  0.0508,  0.0355,  0.0369],
        [ 0.0247,  0.1099,  0.0145,  0.0564],
        [ 0.0620,  0.0623,  0.0016

tensor([[ 0.0462,  0.0544,  0.0553,  0.0438],
        [ 0.0412,  0.0362,  0.0610,  0.0363],
        [ 0.0606,  0.0382,  0.0504,  0.0517],
        [ 0.0362,  0.1090, -0.0186,  0.0580],
        [ 0.0378,  0.0816,  0.0693,  0.0639],
        [ 0.0513,  0.0518,  0.0589,  0.0537],
        [ 0.0408,  0.0630,  0.0647,  0.0572],
        [ 0.0460,  0.0701,  0.0567,  0.0640],
        [ 0.0642,  0.0425,  0.0659,  0.0554],
        [ 0.0447,  0.0532,  0.0600,  0.0609],
        [ 0.0466,  0.0511,  0.0560,  0.0478],
        [ 0.0513,  0.0614,  0.0384,  0.0526],
        [ 0.0345,  0.0568,  0.0494,  0.0509],
        [ 0.0399,  0.0604,  0.0496,  0.0549],
        [ 0.0551,  0.0569,  0.0570,  0.0685],
        [ 0.0298,  0.0518,  0.0737,  0.0481],
        [ 0.0301,  0.0937,  0.0535,  0.0591],
        [-0.0698,  0.2565,  0.0205,  0.0372],
        [ 0.0490,  0.0437,  0.0411,  0.0600],
        [ 0.0573,  0.0579,  0.0219,  0.0630],
        [ 0.0459,  0.0364,  0.0626,  0.0525],
        [ 0.0219,  0.0892,  0.0529

tensor([[ 0.0269,  0.0483,  0.0540,  0.0382],
        [ 0.0402,  0.0601,  0.0593,  0.0582],
        [ 0.0517,  0.0863, -0.0208,  0.0342],
        [ 0.0301,  0.0577,  0.0590,  0.0526],
        [ 0.0432,  0.0608,  0.0597,  0.0533],
        [ 0.0169,  0.0831,  0.0642,  0.0460],
        [ 0.0511,  0.0635,  0.0568,  0.0547],
        [ 0.0185,  0.0507,  0.0782,  0.0352],
        [ 0.0459,  0.0626,  0.0535,  0.0522],
        [ 0.0452,  0.0575,  0.0622,  0.0513],
        [ 0.0457,  0.1104, -0.0166,  0.0487],
        [ 0.0195,  0.1411, -0.0366,  0.0462],
        [ 0.0330,  0.1138,  0.0138,  0.0466],
        [ 0.0493,  0.0680,  0.0650,  0.0545],
        [ 0.0491,  0.0595,  0.0133,  0.0361],
        [ 0.0698,  0.0246,  0.0572,  0.0538],
        [-0.0068,  0.1559,  0.0450,  0.0537],
        [ 0.0573,  0.0567,  0.0573,  0.0511],
        [ 0.0223,  0.0748,  0.0464,  0.0564],
        [ 0.0621,  0.0617,  0.0358,  0.0549],
        [ 0.0567,  0.0493,  0.0536,  0.0627],
        [ 0.0421,  0.0587,  0.0670

tensor([[ 0.0837,  0.0279,  0.0674,  0.0649],
        [ 0.0666,  0.0237,  0.0750,  0.0605],
        [ 0.0881,  0.0316,  0.0505,  0.0625],
        [ 0.0739,  0.0343,  0.0848,  0.0540],
        [ 0.0764,  0.0233,  0.0988,  0.0445],
        [ 0.0705,  0.0288,  0.0691,  0.0576],
        [ 0.0439, -0.0127,  0.2036,  0.0604],
        [ 0.0585,  0.0301,  0.0910,  0.0639],
        [ 0.0501,  0.0551,  0.0875,  0.0778],
        [ 0.0530,  0.0524,  0.0700,  0.0580],
        [ 0.0623,  0.0555,  0.0936,  0.0725],
        [ 0.0289,  0.0835,  0.1027,  0.0759],
        [ 0.0840,  0.0434,  0.0463,  0.0548],
        [ 0.0635,  0.0444,  0.0709,  0.0533],
        [ 0.0524,  0.0585,  0.0895,  0.0787],
        [ 0.0478,  0.0499,  0.0656,  0.0634],
        [ 0.0625,  0.0577,  0.0546,  0.0631],
        [ 0.0348,  0.0519,  0.1566,  0.0731],
        [ 0.0707,  0.0354,  0.0525,  0.0484],
        [ 0.0681,  0.0407,  0.0884,  0.0633],
        [ 0.0523,  0.0252,  0.0924,  0.0630],
        [ 0.0676,  0.0507,  0.0235

tensor([[ 0.0508,  0.0493,  0.0684,  0.0531],
        [ 0.0622,  0.0345,  0.0538,  0.0496],
        [ 0.0489,  0.0503,  0.0619,  0.0478],
        [ 0.0506,  0.0424,  0.1313,  0.0330],
        [ 0.0429,  0.0604,  0.0542,  0.0479],
        [ 0.0675,  0.0205,  0.0654,  0.0430],
        [ 0.0432,  0.0580,  0.0576,  0.0397],
        [ 0.0199,  0.1295,  0.0005,  0.0518],
        [ 0.0513,  0.0621,  0.0347,  0.0383],
        [ 0.0601,  0.0447,  0.0481,  0.0556],
        [ 0.0483,  0.0471,  0.0401,  0.0528],
        [ 0.0645,  0.0570,  0.0749,  0.0404],
        [ 0.0413,  0.0687,  0.0919,  0.0506],
        [ 0.0539,  0.0489,  0.0293,  0.0433],
        [ 0.0814,  0.0387,  0.0731,  0.0477],
        [ 0.0691,  0.0443,  0.0814,  0.0544],
        [ 0.0463,  0.0502,  0.0533,  0.0434],
        [ 0.0645,  0.0349,  0.0503,  0.0474],
        [ 0.0459,  0.0661,  0.1190,  0.0543],
        [ 0.0427,  0.0548,  0.0495,  0.0437],
        [ 0.0444,  0.0504,  0.1333,  0.0341],
        [ 0.0490,  0.0528,  0.0543

tensor([[ 0.0704,  0.0511,  0.0883,  0.0492],
        [ 0.0296,  0.0988, -0.0196,  0.0518],
        [ 0.0479,  0.1038,  0.0473,  0.0647],
        [ 0.0705,  0.0502,  0.0618,  0.0504],
        [ 0.0557,  0.0325, -0.0002,  0.0406],
        [ 0.0430,  0.0702, -0.0052,  0.0490],
        [ 0.0491,  0.0437, -0.0047,  0.0627],
        [ 0.0397,  0.0562,  0.0371,  0.0503],
        [ 0.0502,  0.0660, -0.0340,  0.0474],
        [ 0.0673,  0.0707,  0.0625,  0.0775],
        [ 0.0480,  0.0841,  0.0345,  0.0463],
        [ 0.0512,  0.0449,  0.0333,  0.0492],
        [ 0.0481,  0.0548,  0.0414,  0.0469],
        [ 0.0439,  0.0540,  0.0340,  0.0535],
        [ 0.0339,  0.0812, -0.0186,  0.0536],
        [ 0.0413,  0.0696, -0.0117,  0.0479],
        [ 0.0494,  0.0346,  0.0307,  0.0494],
        [ 0.0517,  0.0731,  0.0322,  0.0497],
        [ 0.0543,  0.0637,  0.0609,  0.0470],
        [ 0.0436,  0.0656,  0.0329,  0.0526],
        [ 0.0216,  0.1218,  0.0343,  0.0376],
        [ 0.0573,  0.0570,  0.0384

tensor([[ 0.0534,  0.0471, -0.0462,  0.0420],
        [ 0.0525,  0.0254,  0.0427,  0.0551],
        [ 0.0484,  0.0374, -0.0118,  0.0495],
        [ 0.0810,  0.0356,  0.0313,  0.0498],
        [ 0.0836,  0.0364,  0.0459,  0.0459],
        [ 0.0392,  0.0941,  0.0024,  0.0533],
        [ 0.0423,  0.0472,  0.0435,  0.0494],
        [ 0.0774,  0.0344,  0.0571,  0.0601],
        [ 0.0825,  0.0224,  0.0636,  0.0501],
        [ 0.0606,  0.0070,  0.0338,  0.0491],
        [ 0.0386,  0.1086, -0.0620,  0.0592],
        [ 0.0518,  0.0540,  0.0326,  0.0442],
        [ 0.0466,  0.0464,  0.0433,  0.0506],
        [ 0.0787,  0.0399,  0.0435,  0.0620],
        [ 0.0557,  0.0513, -0.0651,  0.0564],
        [ 0.0449,  0.0508,  0.0562,  0.0588],
        [ 0.0577,  0.0299,  0.0244,  0.0488],
        [ 0.0441,  0.0246,  0.0468,  0.0476],
        [ 0.0502,  0.0604, -0.0321,  0.0644],
        [ 0.0611,  0.0489,  0.0284,  0.0554],
        [ 0.0532,  0.0628,  0.0360,  0.0430],
        [ 0.0496,  0.0631, -0.0197

tensor([[ 0.0350,  0.0429,  0.0592,  0.0484],
        [ 0.0424,  0.0435,  0.0720,  0.0487],
        [ 0.0431,  0.0660,  0.0224,  0.0425],
        [ 0.0459,  0.0633,  0.0442,  0.0469],
        [ 0.0329,  0.0845,  0.0813,  0.0590],
        [ 0.0492,  0.0647,  0.0520,  0.0504],
        [ 0.0060,  0.1754, -0.0196,  0.0612],
        [ 0.0525,  0.0623,  0.0635,  0.0357],
        [ 0.0431,  0.0683,  0.0455,  0.0506],
        [ 0.0389,  0.0315,  0.0446,  0.0487],
        [ 0.0436,  0.0863,  0.0212,  0.0577],
        [ 0.0634,  0.0493,  0.0505,  0.0498],
        [ 0.0432,  0.0649,  0.0501,  0.0488],
        [ 0.0320,  0.0893,  0.0547,  0.0370],
        [ 0.0434,  0.0577,  0.0448,  0.0441],
        [ 0.0395,  0.1018, -0.0537,  0.0440],
        [ 0.0514,  0.0647,  0.0374,  0.0537],
        [ 0.0511,  0.0533,  0.0540,  0.0361],
        [ 0.0451,  0.0574,  0.0432,  0.0481],
        [ 0.0314,  0.0756,  0.0152,  0.0477],
        [ 0.0458,  0.0672,  0.0384,  0.0435],
        [ 0.0506,  0.0712,  0.0502

tensor([[ 0.0364,  0.0636,  0.0754,  0.0454],
        [ 0.0370,  0.0795,  0.0490,  0.0553],
        [ 0.0447,  0.0575,  0.0363,  0.0407],
        [ 0.0685,  0.0192,  0.0473,  0.0444],
        [ 0.0490,  0.0644,  0.0445,  0.0486],
        [ 0.0480,  0.0740,  0.0346,  0.0486],
        [ 0.0463,  0.0352,  0.0657,  0.0505],
        [ 0.0568,  0.0616, -0.0077,  0.0459],
        [ 0.0585,  0.0456,  0.0404,  0.0444],
        [ 0.0445,  0.0457,  0.0652,  0.0587],
        [ 0.0559,  0.0449,  0.0555,  0.0559],
        [ 0.0402,  0.0438,  0.0603,  0.0531],
        [ 0.0597,  0.0615,  0.0417,  0.0589],
        [ 0.0458,  0.0543,  0.0581,  0.0541],
        [ 0.0436,  0.0351,  0.0628,  0.0517],
        [ 0.0607,  0.0441,  0.0610,  0.0478],
        [ 0.0567,  0.0654,  0.0494,  0.0445],
        [ 0.0604,  0.0396,  0.0585,  0.0575],
        [ 0.0536,  0.0602,  0.0414,  0.0584],
        [ 0.0528,  0.0370,  0.0642,  0.0589],
        [ 0.0504,  0.0605,  0.0403,  0.0595],
        [ 0.0514,  0.0589,  0.0345

tensor(1.00000e-02 *
       [[ 5.8196,  5.0712,  7.0743,  5.6367],
        [ 5.6743,  4.5600,  4.2961,  4.3895],
        [ 6.7244,  3.0980,  5.5487,  4.9590],
        [ 5.8059,  3.9553,  3.2189,  5.0780],
        [ 6.1315,  4.1299,  6.5618,  4.9588],
        [ 5.6926,  4.8333,  4.9821,  5.5342],
        [ 5.6832,  4.7991,  5.2600,  4.8739],
        [ 6.0171,  3.8513,  5.7816,  4.7268],
        [ 4.4460,  6.4272,  5.7946,  5.9293],
        [ 5.1996,  5.7798,  6.4365,  4.6323],
        [ 7.5143,  3.2127,  5.5691,  5.4794],
        [ 6.3015,  5.3070,  6.2655,  6.5959],
        [ 6.3076,  4.4977,  4.8559,  5.4544],
        [ 5.7087,  3.7429,  4.6213,  5.6958],
        [ 7.2672,  4.3249,  5.5437,  5.8283],
        [ 6.4026,  4.4714,  5.1250,  6.0004],
        [ 6.6069,  3.4884,  5.6218,  5.7061],
        [ 5.7803,  5.5877,  4.3463,  6.0927],
        [ 6.8496,  1.9920,  6.1763,  5.3621],
        [ 3.5417,  8.3483,  4.6500,  5.3266],
        [ 7.5224,  3.4463,  5.7012,  6.1399],
        [ 5.8

tensor([[ 0.0457,  0.0518,  0.0665,  0.0463],
        [ 0.0458,  0.0589,  0.0594,  0.0496],
        [ 0.0464,  0.0602,  0.0554,  0.0542],
        [ 0.0543,  0.0884, -0.0589,  0.0441],
        [ 0.0211,  0.1149,  0.0686,  0.0607],
        [ 0.0502,  0.0531,  0.0722,  0.0602],
        [ 0.0652,  0.0567, -0.0065,  0.0411],
        [ 0.0492,  0.0600,  0.0503,  0.0425],
        [ 0.0600,  0.0619,  0.0567,  0.0487],
        [ 0.0497,  0.0553,  0.0500,  0.0568],
        [ 0.0534,  0.0376,  0.0722,  0.0488],
        [ 0.0577,  0.0381,  0.0603,  0.0488],
        [ 0.0553,  0.0837, -0.0409,  0.0362],
        [ 0.0538,  0.0352,  0.0709,  0.0450],
        [ 0.0508,  0.0668,  0.0588,  0.0619],
        [ 0.0521,  0.0472,  0.0656,  0.0557],
        [ 0.0473,  0.0436,  0.0529,  0.0460],
        [ 0.0442,  0.0536,  0.0654,  0.0527],
        [ 0.0430,  0.0665,  0.0890,  0.0506],
        [ 0.0499,  0.0573,  0.0469,  0.0595],
        [ 0.0535,  0.0698,  0.0538,  0.0525],
        [ 0.0472,  0.0511,  0.0553

tensor([[ 0.0609,  0.0422,  0.0581,  0.0504],
        [ 0.0497,  0.0612,  0.0621,  0.0556],
        [ 0.0492,  0.0476,  0.0898,  0.0515],
        [ 0.0489,  0.0250,  0.1111,  0.0317],
        [ 0.0477,  0.0800,  0.0264,  0.0428],
        [ 0.0487,  0.0608,  0.0460,  0.0595],
        [ 0.0443,  0.1069, -0.0006,  0.0564],
        [ 0.0507,  0.0675,  0.0585,  0.0619],
        [ 0.0498,  0.0407,  0.0556,  0.0494],
        [ 0.0363,  0.0682,  0.0801,  0.0536],
        [ 0.0604,  0.0525,  0.0600,  0.0512],
        [ 0.0441,  0.0372,  0.0978,  0.0349],
        [ 0.0600,  0.0390,  0.0935,  0.0551],
        [ 0.0568,  0.0560,  0.0549,  0.0396],
        [ 0.0624,  0.0289,  0.0771,  0.0481],
        [ 0.0425,  0.0862,  0.0436,  0.0485],
        [ 0.0462,  0.0631,  0.0621,  0.0617],
        [ 0.0432,  0.0639,  0.1049,  0.0664],
        [ 0.0549,  0.0483,  0.0741,  0.0608],
        [ 0.0386,  0.0603,  0.0728,  0.0595],
        [ 0.0444,  0.0620,  0.0579,  0.0560],
        [ 0.0302,  0.0864,  0.0620

tensor([[ 0.0540,  0.0543,  0.0474,  0.0468],
        [ 0.0501,  0.0327,  0.0721,  0.0501],
        [ 0.0485,  0.0636,  0.0357,  0.0534],
        [ 0.0489,  0.0599,  0.0467,  0.0593],
        [ 0.0592,  0.0464,  0.0506,  0.0515],
        [ 0.0566,  0.0430,  0.0499,  0.0502],
        [ 0.0641,  0.0244,  0.0545,  0.0569],
        [ 0.0607,  0.0412,  0.0519,  0.0612],
        [ 0.0532,  0.0480,  0.0570,  0.0591],
        [-0.0740,  0.3120,  0.0057,  0.0156],
        [ 0.0504,  0.0591,  0.0562,  0.0621],
        [ 0.0506,  0.0511,  0.0628,  0.0506],
        [ 0.0535,  0.0327,  0.0451,  0.0460],
        [ 0.0628,  0.0461,  0.0382,  0.0576],
        [ 0.0524,  0.0601,  0.0438,  0.0577],
        [ 0.0572,  0.0581,  0.0387,  0.0491],
        [ 0.0493,  0.0533,  0.0560,  0.0577],
        [ 0.0478,  0.0792,  0.0367,  0.0533],
        [ 0.0550,  0.0428,  0.0587,  0.0517],
        [ 0.0584,  0.0506,  0.0530,  0.0487],
        [ 0.0546,  0.0608,  0.0406,  0.0511],
        [ 0.0592,  0.0941,  0.0385

tensor([[ 0.0568,  0.0579,  0.0612,  0.0584],
        [ 0.0667,  0.0464,  0.0436,  0.0500],
        [ 0.0486,  0.0694,  0.0453,  0.0620],
        [ 0.0589,  0.0352,  0.0348,  0.0445],
        [ 0.0244,  0.1291,  0.0320,  0.0561],
        [ 0.0478,  0.0312,  0.0245,  0.0367],
        [ 0.0658,  0.0548,  0.0299,  0.0669],
        [ 0.0628,  0.0572,  0.0416,  0.0549],
        [ 0.0498,  0.0869,  0.0152,  0.0689],
        [ 0.0536,  0.0419,  0.0588,  0.0584],
        [ 0.0571,  0.0600,  0.0437,  0.0588],
        [ 0.0563,  0.0466,  0.0541,  0.0602],
        [ 0.0594,  0.0635,  0.0363,  0.0566],
        [ 0.0540,  0.0381,  0.0439,  0.0439],
        [ 0.0620,  0.0473,  0.0165,  0.0634],
        [ 0.0570,  0.0626,  0.0440,  0.0522],
        [ 0.0615,  0.0580,  0.0280,  0.0578],
        [ 0.0548,  0.0578,  0.0423,  0.0579],
        [ 0.0500,  0.0472,  0.0149,  0.0477],
        [ 0.0510,  0.0654,  0.0455,  0.0568],
        [ 0.0621,  0.0405,  0.0456,  0.0554],
        [ 0.0584,  0.0453,  0.0566

tensor([[ 0.0515,  0.0577,  0.0557,  0.0613],
        [ 0.0562,  0.0479,  0.0443,  0.0572],
        [ 0.0515,  0.0518,  0.0489,  0.0453],
        [ 0.0624,  0.0388,  0.0476,  0.0533],
        [ 0.0532,  0.0647,  0.0450,  0.0564],
        [ 0.0506,  0.0662,  0.0318,  0.0533],
        [ 0.0394,  0.0926,  0.0256,  0.0569],
        [ 0.0471,  0.0617,  0.0465,  0.0570],
        [ 0.0477,  0.0631,  0.0126,  0.0526],
        [ 0.0491,  0.0690,  0.0347,  0.0505],
        [ 0.0517,  0.0519,  0.0570,  0.0606],
        [ 0.0640,  0.0269,  0.0196,  0.0559],
        [ 0.0509,  0.0849,  0.0323,  0.0496],
        [ 0.0622,  0.0500,  0.0423,  0.0598],
        [ 0.0554,  0.0655,  0.0617,  0.0585],
        [ 0.0470,  0.0464,  0.0643,  0.0504],
        [ 0.0533,  0.0587,  0.0236,  0.0532],
        [ 0.0569,  0.0516,  0.0627,  0.0449],
        [ 0.0592,  0.0480,  0.0547,  0.0497],
        [ 0.0660,  0.0447,  0.0783,  0.0567],
        [ 0.0577,  0.0744,  0.0232,  0.0516],
        [ 0.0303,  0.1418,  0.0167

tensor([[ 0.0510,  0.0560,  0.0427,  0.0461],
        [ 0.0500,  0.0650,  0.0488,  0.0512],
        [ 0.0434,  0.0769,  0.0522,  0.0587],
        [ 0.0418,  0.0922,  0.0368,  0.0523],
        [ 0.0450,  0.0724,  0.0515,  0.0548],
        [ 0.0466,  0.0635,  0.0663,  0.0633],
        [ 0.0456,  0.1392, -0.0022,  0.0636],
        [ 0.0451,  0.0547,  0.0681,  0.0517],
        [ 0.0492,  0.0811,  0.0531,  0.0497],
        [ 0.0554,  0.0511,  0.0571,  0.0519],
        [ 0.0532,  0.0542,  0.0479,  0.0539],
        [ 0.0521,  0.0638,  0.0461,  0.0403],
        [ 0.0267,  0.1279,  0.0303,  0.0419],
        [ 0.0545,  0.0527,  0.0498,  0.0464],
        [ 0.0370,  0.1012,  0.0279,  0.0540],
        [ 0.0482,  0.0661,  0.0420,  0.0402],
        [ 0.0586,  0.0606,  0.0475,  0.0529],
        [ 0.0392,  0.1041,  0.0478,  0.0577],
        [ 0.0474,  0.0653,  0.0678,  0.0443],
        [ 0.0473,  0.0592,  0.0610,  0.0449],
        [ 0.0531,  0.0773,  0.0306,  0.0593],
        [ 0.0443,  0.1248,  0.0403

tensor([[ 0.0490,  0.0607,  0.0386,  0.0447],
        [ 0.0642,  0.0583,  0.0607,  0.0543],
        [ 0.0484,  0.0733,  0.0769,  0.0628],
        [ 0.0556,  0.0926,  0.0316,  0.0548],
        [ 0.0391,  0.1070,  0.0747,  0.0646],
        [ 0.0718,  0.0588,  0.0704,  0.0488],
        [ 0.0399,  0.0878,  0.0721,  0.0538],
        [ 0.0642,  0.0535,  0.0696,  0.0491],
        [ 0.0627,  0.0284,  0.0536,  0.0518],
        [ 0.0468,  0.0709,  0.0754,  0.0606],
        [ 0.0528,  0.0639,  0.0923,  0.0585],
        [ 0.0653,  0.0697,  0.0801,  0.0570],
        [ 0.0656,  0.0550,  0.0677,  0.0538],
        [ 0.0632,  0.0486,  0.0503,  0.0455],
        [ 0.0551,  0.0837,  0.0645,  0.0530],
        [ 0.0686,  0.0405,  0.0655,  0.0504],
        [ 0.0623,  0.0388,  0.0691,  0.0527],
        [ 0.0574,  0.0789,  0.0557,  0.0574],
        [ 0.0614,  0.0448,  0.0615,  0.0471],
        [ 0.0660,  0.0442,  0.0761,  0.0459],
        [ 0.0373,  0.1673,  0.0333,  0.0565],
        [ 0.0582,  0.0341,  0.0551

tensor([[ 0.0716,  0.0246,  0.0620,  0.0482],
        [ 0.0510,  0.0491,  0.0658,  0.0560],
        [ 0.0605,  0.0367,  0.0615,  0.0434],
        [ 0.0595,  0.0528,  0.0636,  0.0527],
        [ 0.0548,  0.0262,  0.0686,  0.0546],
        [ 0.0559,  0.0290,  0.0694,  0.0543],
        [ 0.0515,  0.0666,  0.0611,  0.0513],
        [ 0.0556,  0.0297,  0.0729,  0.0495],
        [ 0.0200,  0.1775,  0.0460,  0.0581],
        [ 0.0608,  0.0510,  0.1035,  0.0427],
        [ 0.0652,  0.0313,  0.0708,  0.0492],
        [ 0.0515,  0.0643,  0.0514,  0.0519],
        [ 0.0820,  0.0242,  0.0718,  0.0549],
        [ 0.0579,  0.0461,  0.0639,  0.0459],
        [ 0.0677,  0.0422,  0.0612,  0.0538],
        [ 0.0548,  0.0363,  0.0942,  0.0498],
        [ 0.0562,  0.0572,  0.0681,  0.0550],
        [ 0.0672,  0.0839, -0.0177,  0.0346],
        [ 0.0429,  0.0810,  0.0694,  0.0594],
        [ 0.0471,  0.0388,  0.0857,  0.0573],
        [ 0.0493,  0.0951,  0.0309,  0.0443],
        [ 0.0658,  0.0628,  0.0428

tensor([[ 0.0283,  0.1114,  0.0573,  0.0653],
        [ 0.0373,  0.0505,  0.0704,  0.0454],
        [ 0.0454,  0.0302,  0.0618,  0.0541],
        [ 0.0445,  0.0332,  0.0599,  0.0502],
        [ 0.0376,  0.0750,  0.0625,  0.0604],
        [ 0.0464,  0.0571,  0.0402,  0.0541],
        [ 0.0410,  0.0784,  0.0557,  0.0590],
        [ 0.0427,  0.0555,  0.0615,  0.0549],
        [ 0.0490,  0.0825,  0.0465,  0.0600],
        [ 0.0245,  0.0617,  0.0759,  0.0524],
        [ 0.0493,  0.0770,  0.0485,  0.0395],
        [ 0.0650,  0.0499,  0.0507,  0.0540],
        [ 0.0381,  0.0447,  0.0637,  0.0499],
        [ 0.0223,  0.0965,  0.1138,  0.0535],
        [ 0.0550,  0.0483,  0.0492,  0.0575],
        [ 0.0486,  0.0486,  0.0749,  0.0632],
        [ 0.0378,  0.1099,  0.0469,  0.0365],
        [ 0.0426,  0.0513,  0.0561,  0.0529],
        [ 0.0310,  0.0940,  0.0557,  0.0631],
        [ 0.0025,  0.2553, -0.0435,  0.0490],
        [ 0.0507,  0.0605,  0.0483,  0.0558],
        [ 0.0461,  0.0586,  0.0427

tensor([[ 0.0623,  0.0377,  0.0387,  0.0479],
        [ 0.0523,  0.0586,  0.0609,  0.0550],
        [ 0.0494,  0.0464,  0.0509,  0.0562],
        [ 0.0448,  0.0473,  0.0484,  0.0572],
        [ 0.0511,  0.0561,  0.0637,  0.0604],
        [ 0.0686,  0.0545,  0.0315,  0.0654],
        [ 0.0432,  0.0254,  0.0738,  0.0515],
        [ 0.0554,  0.0364,  0.0487,  0.0600],
        [ 0.0658,  0.0510,  0.0303,  0.0587],
        [ 0.0547,  0.0599,  0.0323,  0.0593],
        [ 0.0476,  0.0772,  0.0447,  0.0662],
        [ 0.0540,  0.0721,  0.0332,  0.0540],
        [ 0.0466,  0.1279, -0.1064,  0.0391],
        [ 0.0677,  0.0134,  0.0630,  0.0576],
        [ 0.0667,  0.0539,  0.0498,  0.0592],
        [ 0.0683,  0.0474,  0.0546,  0.0611],
        [ 0.0609,  0.0527,  0.0304,  0.0591],
        [ 0.0437,  0.0325,  0.0582,  0.0583],
        [ 0.0514,  0.0740,  0.0501,  0.0644],
        [ 0.0706,  0.0646,  0.0396,  0.0610],
        [ 0.0737,  0.0321,  0.0384,  0.0569],
        [ 0.0592,  0.0647,  0.0343

tensor([[ 0.0642,  0.0650,  0.0219,  0.0593],
        [ 0.0675,  0.0617,  0.0573,  0.0607],
        [ 0.0377,  0.0988,  0.0555,  0.0574],
        [ 0.0582,  0.0321,  0.0336,  0.0335],
        [ 0.0535,  0.0646,  0.0410,  0.0528],
        [ 0.0495,  0.0324,  0.0392,  0.0485],
        [ 0.0570,  0.0523,  0.0524,  0.0548],
        [ 0.0449,  0.0578,  0.0508,  0.0550],
        [ 0.0541,  0.0771,  0.0337,  0.0576],
        [ 0.0545,  0.0594,  0.0347,  0.0553],
        [ 0.0492,  0.0787,  0.0395,  0.0526],
        [ 0.0762,  0.0262,  0.0187,  0.0628],
        [ 0.0601,  0.0597,  0.0413,  0.0605],
        [ 0.0633,  0.0273,  0.0455,  0.0541],
        [ 0.0600,  0.0778,  0.0243,  0.0640],
        [ 0.0363,  0.1010,  0.0437,  0.0509],
        [ 0.0539,  0.0596,  0.0340,  0.0520],
        [ 0.0491,  0.0608,  0.0462,  0.0568],
        [ 0.0367,  0.1080,  0.0124,  0.0405],
        [ 0.0573,  0.0493,  0.0432,  0.0418],
        [ 0.0541,  0.0648,  0.0370,  0.0545],
        [ 0.0639,  0.0621,  0.0277

tensor([[ 0.0541,  0.0319,  0.0267,  0.0378],
        [ 0.0436,  0.0814,  0.0473,  0.0554],
        [ 0.0588,  0.0614,  0.0380,  0.0569],
        [ 0.0474,  0.0458,  0.0468,  0.0532],
        [ 0.0630,  0.0400,  0.0533,  0.0438],
        [ 0.0517,  0.0807,  0.0557,  0.0548],
        [ 0.0505,  0.0771,  0.0371,  0.0509],
        [ 0.0459,  0.0636,  0.0433,  0.0542],
        [ 0.0496,  0.0663,  0.0452,  0.0568],
        [ 0.0719,  0.0464,  0.0356,  0.0523],
        [ 0.0665,  0.0535,  0.0194,  0.0514],
        [ 0.0510,  0.0879,  0.0088,  0.0549],
        [ 0.0602,  0.0585,  0.0402,  0.0573],
        [ 0.0616,  0.0383,  0.0392,  0.0587],
        [ 0.0553,  0.0537,  0.0592,  0.0574],
        [ 0.0531,  0.0620,  0.0319,  0.0483],
        [ 0.0616,  0.0538,  0.0503,  0.0500],
        [ 0.0463,  0.0512,  0.0458,  0.0471],
        [ 0.0559,  0.0451,  0.0342,  0.0468],
        [ 0.0402,  0.0177,  0.0425,  0.0413],
        [ 0.0341,  0.1294,  0.0083,  0.0482],
        [ 0.0399,  0.1275, -0.0449

tensor([[ 0.0661,  0.0307, -0.0193,  0.0379],
        [ 0.0554,  0.0531,  0.0517,  0.0555],
        [ 0.0531,  0.0489,  0.0470,  0.0558],
        [ 0.0634,  0.0290,  0.0535,  0.0474],
        [ 0.0488,  0.1143, -0.0270,  0.0433],
        [ 0.0513,  0.0621,  0.0135,  0.0486],
        [ 0.0640,  0.0494,  0.0056,  0.0481],
        [ 0.0628,  0.0209,  0.0386,  0.0371],
        [ 0.0557,  0.0304,  0.0545,  0.0522],
        [ 0.0506,  0.0457,  0.0665,  0.0518],
        [ 0.0369,  0.1058,  0.0488,  0.0523],
        [ 0.0490,  0.0370,  0.0601,  0.0574],
        [ 0.0555,  0.0465,  0.0460,  0.0612],
        [ 0.0545,  0.0481,  0.0286,  0.0587],
        [ 0.0633,  0.0510,  0.0167,  0.0545],
        [ 0.0418,  0.0329,  0.0773,  0.0433],
        [ 0.0656,  0.0459,  0.0482,  0.0562],
        [ 0.0653,  0.0298,  0.0489,  0.0436],
        [ 0.0595,  0.0386,  0.0522,  0.0542],
        [ 0.0571,  0.0463,  0.0723,  0.0458],
        [ 0.0490,  0.0367,  0.0385,  0.0510],
        [ 0.0590,  0.0461,  0.0235

tensor([[ 0.0447,  0.0548,  0.0555,  0.0464],
        [ 0.0668, -0.0020,  0.0741,  0.0496],
        [ 0.0561,  0.0461,  0.0637,  0.0561],
        [ 0.0572,  0.0364,  0.0692,  0.0595],
        [ 0.0532,  0.0426,  0.0713,  0.0551],
        [ 0.0405,  0.0502,  0.0396,  0.0459],
        [ 0.0511,  0.0109,  0.0843,  0.0538],
        [ 0.0466,  0.0526,  0.0569,  0.0614],
        [ 0.0659,  0.0401,  0.0622,  0.0579],
        [ 0.0623,  0.0184,  0.0539,  0.0541],
        [ 0.0476,  0.0551,  0.0572,  0.0459],
        [ 0.0492,  0.0540,  0.0608,  0.0462],
        [ 0.0653,  0.0441,  0.0841,  0.0625],
        [ 0.0538,  0.0552,  0.0635,  0.0517],
        [ 0.0578,  0.0458,  0.0717,  0.0572],
        [ 0.0525,  0.0009,  0.0295,  0.0301],
        [ 0.0652,  0.0171,  0.0663,  0.0562],
        [ 0.0472, -0.0021,  0.0648,  0.0447],
        [ 0.0450,  0.0333,  0.0484,  0.0420],
        [ 0.0536,  0.0158,  0.0777,  0.0483],
        [ 0.0506,  0.0493,  0.0566,  0.0475],
        [ 0.0541,  0.0591,  0.0833

tensor([[ 0.0421,  0.0441,  0.0670,  0.0552],
        [ 0.0485,  0.0452,  0.0611,  0.0506],
        [ 0.0539,  0.0633,  0.0577,  0.0670],
        [ 0.0573,  0.0391,  0.0546,  0.0532],
        [ 0.0550,  0.0626,  0.0623,  0.0568],
        [ 0.0476,  0.0538,  0.0653,  0.0650],
        [ 0.0559,  0.0417,  0.0472,  0.0533],
        [ 0.0472,  0.0686,  0.0560,  0.0485],
        [ 0.0393,  0.0929,  0.0543,  0.0559],
        [ 0.0519,  0.0648,  0.0611,  0.0603],
        [ 0.0511,  0.0541,  0.0579,  0.0666],
        [ 0.0470,  0.0910,  0.0959,  0.0705],
        [ 0.0545,  0.0478,  0.0417,  0.0549],
        [ 0.0627,  0.0892,  0.0049,  0.0494],
        [ 0.0424,  0.0531,  0.0668,  0.0622],
        [ 0.0558,  0.0590,  0.0902,  0.0595],
        [ 0.0587,  0.0601,  0.0936,  0.0480],
        [ 0.0158,  0.1859, -0.1837,  0.0690],
        [ 0.0471,  0.0680,  0.0504,  0.0480],
        [ 0.0517,  0.0819,  0.0491,  0.0610],
        [ 0.0476,  0.0667,  0.0515,  0.0690],
        [ 0.0505,  0.0534,  0.0576

tensor([[ 0.0527,  0.0480,  0.0491,  0.0549],
        [ 0.0625,  0.0564,  0.0670,  0.0556],
        [ 0.0584,  0.0596,  0.0588,  0.0481],
        [ 0.0639,  0.0498,  0.0504,  0.0511],
        [ 0.0630,  0.0443,  0.0453,  0.0529],
        [ 0.0530,  0.0581,  0.0311,  0.0590],
        [ 0.0538,  0.0488,  0.0333,  0.0452],
        [ 0.0636,  0.0499,  0.0771,  0.0515],
        [ 0.0680,  0.0716,  0.1510,  0.0540],
        [ 0.0590,  0.0591,  0.0636,  0.0498],
        [ 0.0572,  0.0749,  0.0811,  0.0458],
        [ 0.0452,  0.0675,  0.0651,  0.0612],
        [ 0.0559,  0.0540,  0.0583,  0.0485],
        [ 0.0640,  0.0441,  0.0655,  0.0459],
        [ 0.0687,  0.0500,  0.1083,  0.0550],
        [ 0.0715,  0.0346, -0.0548,  0.0310],
        [ 0.0713,  0.0393,  0.1010,  0.0595],
        [ 0.0723,  0.0180,  0.0643,  0.0628],
        [ 0.0607,  0.0414,  0.0639,  0.0620],
        [ 0.0611,  0.0563,  0.0784,  0.0391],
        [ 0.0547,  0.0461,  0.0543,  0.0581],
        [ 0.0638,  0.0568,  0.0218

tensor([[ 0.0491,  0.0550,  0.0531,  0.0584],
        [ 0.0513,  0.0584,  0.0506,  0.0463],
        [ 0.0397,  0.1442, -0.1274,  0.0357],
        [ 0.0521,  0.0306,  0.0744,  0.0504],
        [ 0.0654,  0.0188,  0.0815,  0.0455],
        [ 0.0649,  0.0509,  0.0516,  0.0544],
        [ 0.0671,  0.0350,  0.0703,  0.0549],
        [ 0.0495,  0.0763,  0.0682,  0.0588],
        [ 0.0588,  0.0901, -0.0422,  0.0346],
        [ 0.0640,  0.0548,  0.0539,  0.0521],
        [ 0.0578,  0.0612,  0.0552,  0.0606],
        [ 0.0471,  0.0654,  0.0536,  0.0436],
        [ 0.0777,  0.0395,  0.0776,  0.0553],
        [ 0.0540,  0.0406,  0.0559,  0.0612],
        [ 0.0555,  0.0709,  0.0673,  0.0519],
        [ 0.0571,  0.0237,  0.0549,  0.0336],
        [ 0.0540,  0.0337,  0.0340,  0.0492],
        [ 0.0528,  0.0641,  0.0523,  0.0515],
        [ 0.0520,  0.0501,  0.0701,  0.0495],
        [ 0.0512,  0.0712,  0.0532,  0.0562],
        [ 0.0441,  0.0335,  0.0531,  0.0457],
        [ 0.0505,  0.0730,  0.0595

tensor([[ 0.0564,  0.0488,  0.0438,  0.0591],
        [ 0.0478,  0.0708,  0.0668,  0.0647],
        [ 0.0530,  0.0538,  0.0179,  0.0627],
        [ 0.0574,  0.0900,  0.0285,  0.0590],
        [ 0.0476,  0.0638,  0.0458,  0.0637],
        [ 0.0381,  0.0544,  0.0226,  0.0596],
        [ 0.0445,  0.0662,  0.0422,  0.0519],
        [ 0.0476,  0.0566,  0.0274,  0.0577],
        [ 0.0491,  0.0250,  0.0870,  0.0507],
        [ 0.0655,  0.0811, -0.0032,  0.0497],
        [ 0.0408,  0.0138,  0.0370,  0.0381],
        [ 0.0419,  0.1068, -0.2803,  0.0373],
        [ 0.0509,  0.0583,  0.0650,  0.0645],
        [ 0.0596,  0.0280,  0.0504,  0.0531],
        [ 0.0589,  0.0472,  0.0084,  0.0546],
        [ 0.0470,  0.0437,  0.0814,  0.0622],
        [ 0.0491,  0.0634,  0.0596,  0.0655],
        [ 0.0364,  0.0496,  0.0203,  0.0592],
        [ 0.0442,  0.0589,  0.0394,  0.0545],
        [ 0.0422,  0.0500,  0.0242,  0.0590],
        [ 0.0459,  0.0520,  0.0474,  0.0497],
        [ 0.0481,  0.0580,  0.0612

tensor([[ 0.0548,  0.0550,  0.0516,  0.0439],
        [ 0.0473,  0.0777,  0.0821,  0.0717],
        [ 0.0586,  0.0390,  0.0540,  0.0628],
        [ 0.0460,  0.0788,  0.0935,  0.0712],
        [ 0.0576,  0.0524,  0.0418,  0.0531],
        [ 0.0602,  0.0778,  0.0805,  0.0605],
        [ 0.0427,  0.0756,  0.0488,  0.0570],
        [ 0.0577,  0.0572,  0.0606,  0.0585],
        [ 0.0492,  0.0756,  0.0510,  0.0580],
        [ 0.0479,  0.0551,  0.0582,  0.0602],
        [ 0.0463,  0.0820,  0.0952,  0.0667],
        [ 0.0538,  0.0672,  0.0630,  0.0513],
        [ 0.0494,  0.0613,  0.0807,  0.0600],
        [ 0.0520,  0.0657,  0.0503,  0.0576],
        [ 0.0484,  0.0451,  0.0658,  0.0594],
        [ 0.0665,  0.0627,  0.1071,  0.0636],
        [ 0.0448,  0.0890,  0.0467,  0.0645],
        [ 0.0525,  0.0638,  0.0174,  0.0585],
        [ 0.0470,  0.0741,  0.0871,  0.0681],
        [ 0.0555,  0.0350,  0.0316,  0.0570],
        [ 0.0577,  0.0438,  0.0298,  0.0581],
        [ 0.0486,  0.0453,  0.0504

KeyboardInterrupt: 

Once trained, let's look at the learning curve

In [ ]:
# plot the scores
plot_results([vanilla_scores, ddqn_scores])

When finished, you can close the environment.

In [ ]:
env.close()